version: '2'
services:
  data:
    image: busybox
    volumes:
      - ../../:/app
  app:
    image: kesshin/php70
    volumes_from:
      - data
    tty: true
    command: php-fpm
  webserver:
    image: nginx
    links:
      - app:app
    volumes_from:
      - data
    volumes:
      - ../configuration/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8083:80