version: '2'
services:
  data:
    image: busybox
    volumes:
      - ../../:/app
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - ../../mysql_data:/var/lib/mysql
  app:
    image: kesshin/php70
    volumes_from:
      - data
    tty: true
    links:
      - db:db
    command: php-fpm
  webserver:
    image: nginx
    links:
      - app:app
    volumes_from:
      - data
    volumes:
      - ../configuration/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80